// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fieldpath.proto

#include "fieldpath.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace containerd {
namespace plugin {
}  // namespace plugin
}  // namespace containerd
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_fieldpath_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_fieldpath_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_fieldpath_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_fieldpath_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_fieldpath_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017fieldpath.proto\022\021containerd.plugin\032 go"
  "ogle/protobuf/descriptor.proto:5\n\rfieldp"
  "ath_all\022\034.google.protobuf.FileOptions\030\304\356"
  "\003 \001(\010:4\n\tfieldpath\022\037.google.protobuf.Mes"
  "sageOptions\030\220\367\003 \001(\010"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_fieldpath_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_fieldpath_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_fieldpath_2eproto_once;
static bool descriptor_table_fieldpath_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fieldpath_2eproto = {
  &descriptor_table_fieldpath_2eproto_initialized, descriptor_table_protodef_fieldpath_2eproto, "fieldpath.proto", 179,
  &descriptor_table_fieldpath_2eproto_once, descriptor_table_fieldpath_2eproto_sccs, descriptor_table_fieldpath_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_fieldpath_2eproto::offsets,
  file_level_metadata_fieldpath_2eproto, 0, file_level_enum_descriptors_fieldpath_2eproto, file_level_service_descriptors_fieldpath_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_fieldpath_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_fieldpath_2eproto), true);
namespace containerd {
namespace plugin {
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  fieldpath_all(kFieldpathAllFieldNumber, false);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  fieldpath(kFieldpathFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)
}  // namespace plugin
}  // namespace containerd
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
